# Generated by Django 5.0.6 on 2024-08-15 17:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task_category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=40)),
                ('task_description', models.CharField(max_length=40)),
                ('is_completed', models.BooleanField(default=False)),
                ('task_assint_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('categories', models.ManyToManyField(related_name='tasks', to='task_category.category')),
            ],
        ),
    ]
